### ISSUE TITLE
Get logs and other info from pods that exit ungracefully

### ISSUE THREAD

**Issue by calebevans** [podmortem/operator#1]
This is going to be the basic function of this operator. We will need to:

- [ ]  Initialize the repository.
- [ ] Add a new CRD to define pods to watch based on a selector.
- [ ] Watch the pods from the new CRD, if they exit ungracefully, gather information:
    - [ ] Logs
    - [ ] Deployment config?
    - [ ] (find other helpful info)
- [ ] Package that information into a predictable format and send it to the backend for processing.

### New CRD Example

```yaml
apiVersion: "redhat.redhat.com/v1alpha1"
kind: "PodmortemConfig"
metadata:
	name: "my-pod-watcher"
	namespace: default
spec:
	podSelector:
	    matchLabels:
		app: my-critical-app
```
