### ISSUE TITLE
Create the `PatternLibrary` Custom Resource

### ISSUE THREAD

**Issue by calebevans** [podmortem/operator#4]
Example of the CR I am thinking of:

```yaml
apiVersion: podmortem.io/v1
kind: PatternLibrary
metadata:
  name: community-patterns
  namespace: podmortem-system
spec:
  repositories:
    - name: "podmortem-community"
      url: "https://github.com/podmortem/pattern-libraries.git"
      branch: "main"
    - name: "enterprise-patterns"
      url: "https://github.com/myorg/private-patterns.git"
      branch: "main"
      credentials:
        secretRef: "git-secret"
  refreshInterval: "30m"
  enabledLibraries:
    - "spring-boot-core"
    - "kubernetes-events"
    - "postgresql-errors"
```
